name: Build
on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_release:
        description: 'Test release?'
        required: true
        default: 'false'

jobs:
  build-ubuntu:
    name: JitterbugPair (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Dependencies
        run: sudo apt install meson libgcrypt-dev libusbmuxd-dev libimobiledevice-dev libunistring-dev
      - name: Build
        run: meson --prefix /usr --buildtype=release build && cd build && ninja
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: jitterbugpair-linux
          path: build/jitterbugpair
  package-pair:
    name: Package JitterbugPair
    runs-on: ubuntu-latest
    needs: [build-ubuntu]
    if: github.event_name == 'release' || github.event.inputs.test_release == 'true'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
      - name: Fix Permissions
        run: for i in jitterbugpair-*/; do chmod +x $i/* ; zip -r -j "${i%/}.zip" "$i"; done
      - name: Upload Linux
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: jitterbugpair-linux.zip
          asset_name: jitterbugpair-linux.zip
          asset_content_type: application/octet-stream
